 export const usuarios = [
  {
    apellidos: "Nicolas ",
    nombres: " Raffagnini",
    email: "nicolas.raffagnini95@gmail.com",
    emailValido: true,
    rol: "PM",
    staff: false,
  },
  {
    apellidos: "Mc Glory ",
    nombres: "Tovar",
    email: "mcglorytovar@gmail.com",
    emailValido: true,
    rol: "QA",
    staff: false,
  },
  {
    apellidos: "Marcelo Alejandro",
    nombres: " Saiz",
    email: "kaosinc@gmail.com",
    emailValido: true,
    rol: "QA",
    staff: false,
  },
  {
    apellidos: "David ",
    nombres: " Gauthier",
    email: "deberia dar error al no tener mail",
    emailValido: false,
    rol: "UX/UI",
    staff: false,
  },
  {
    apellidos: "Alejandro ",
    nombres: " Dominguez",
    email: "alejodi@gmail.com",
    emailValido: true,
    rol: "Backend",
    staff: false,
  },
  {
    apellidos: "Ana ",
    nombres: " Merlo",
    email: "anamerlo_me@hotmail.com",
    emailValido: true,
    rol: "Backend",
    staff: false,
  },
  {
    apellidos: "Efrén ",
    nombres: " Morales",
    email: "efren.morales.flores@gmail.com",
    emailValido: true,
    rol: "Backend",
    staff: false,
  },
  {
    apellidos: "Francisco ",
    nombres: " Sierra",
    email: "fandres6262@gmail.com",
    emailValido: true,
    rol: "Backend",
    staff: false,
  },
  {
    apellidos: "Mario ",
    nombres: " Calderon",
    email: "mario.2893@hotmail.com",
    emailValido: true,
    rol: "Backend",
    staff: false,
  },
  {
    apellidos: "Sturniolo",
    nombres: "Bruno",
    email: "brunosebastian.sturniolo@gmail.com",
    emailValido: true,
    rol: "Backend",
    staff: false,
  },
  {
    apellidos: "Martinez",
    nombres: "Camilo",
    email: "camilom200107@gmail.com",
    emailValido: true,
    rol: "Frontend",
    staff: false,
  },
  {
    apellidos: "Suarez",
    nombres: "Emerson",
    email: "emersonsuarez2904@gmail.com",
    emailValido: true,
    rol: "Frontend",
    staff: false,
  },
  {
    apellidos: "Franco",
    nombres: "Amicone",
    email: "francoamicone1@gmail.com",
    emailValido: true,
    rol: "Frontend",
    staff: false,
  },
  {
    apellidos: "Ravarotto ",
    nombres: "Germán",
    email: "g44ravarotto@gmail.com",
    emailValido: true,
    rol: "Frontend",
    staff: false,
  },
  {
    apellidos: "Contreras",
    nombres: "Salomón Contreras",
    email: "contrerassalomon6@gmail.com",
    emailValido: true,
    rol: "Frontend",
    staff: false,
  },
  {
    apellidos: "Hurtado Testa",
    nombres: "  Testa",
    email: "alejohurtadotesta@gmail.com",
    emailValido: true,
    rol: "Frontend",
    staff: false,
  },
];
